export const allLanguages = [
    { name: "Unknown languages", slug: "unknown" },
    { name: "1C Enterprise", slug: "1c-enterprise" },
    { name: "2-Dimensional Array", slug: "2-dimensional-array" },
    { name: "4D", slug: "4d" },
    { name: "ABAP", slug: "abap" },
    { name: "ABAP CDS", slug: "abap-cds" },
    { name: "ABNF", slug: "abnf" },
    { name: "ActionScript", slug: "actionscript" },
    { name: "Ada", slug: "ada" },
    { name: "Adblock Filter List", slug: "adblock-filter-list" },
    { name: "Adobe Font Metrics", slug: "adobe-font-metrics" },
    { name: "Agda", slug: "agda" },
    { name: "AGS Script", slug: "ags-script" },
    { name: "AIDL", slug: "aidl" },
    { name: "AL", slug: "al" },
    { name: "Alloy", slug: "alloy" },
    { name: "Alpine Abuild", slug: "alpine-abuild" },
    { name: "Altium Designer", slug: "altium-designer" },
    { name: "AMPL", slug: "ampl" },
    { name: "AngelScript", slug: "angelscript" },
    { name: "Ant Build System", slug: "ant-build-system" },
    {
        name: "Antlers",
        slug: "antlers",
    },
    { name: "ANTLR", slug: "antlr" },
    { name: "ApacheConf", slug: "apacheconf" },
    { name: "Apex", slug: "apex" },
    { name: "API Blueprint", slug: "api-blueprint" },
    { name: "APL", slug: "apl" },
    { name: "Apollo Guidance Computer", slug: "apollo-guidance-computer" },
    { name: "AppleScript", slug: "applescript" },
    { name: "Arc", slug: "arc" },
    { name: "AsciiDoc", slug: "asciidoc" },
    { name: "ASL", slug: "asl" },
    { name: "ASN.1", slug: "asn.1" },
    { name: "Classic ASP", slug: "classic-asp" },
    { name: "ASP.NET", slug: "asp.net" },
    { name: "AspectJ", slug: "aspectj" },
    { name: "Assembly", slug: "assembly" },
    { name: "Astro", slug: "astro" },
    { name: "Asymptote", slug: "asymptote" },
    { name: "ATS", slug: "ats" },
    { name: "Augeas", slug: "augeas" },
    { name: "AutoHotkey", slug: "autohotkey" },
    { name: "AutoIt", slug: "autoit" },
    { name: "Avro IDL", slug: "avro-idl" },
    { name: "Awk", slug: "awk" },
    {
        name: "Ballerina",
        slug: "ballerina",
    },
    { name: "BASIC", slug: "basic" },
    { name: "Batchfile", slug: "batchfile" },
    { name: "Beef", slug: "beef" },
    { name: "Befunge", slug: "befunge" },
    { name: "Berry", slug: "berry" },
    { name: "BibTeX", slug: "bibtex" },
    { name: "Bicep", slug: "bicep" },
    { name: "Bikeshed", slug: "bikeshed" },
    { name: "Bison", slug: "bison" },
    { name: "BitBake", slug: "bitbake" },
    { name: "Blade", slug: "blade" },
    { name: "BlitzBasic", slug: "blitzbasic" },
    { name: "BlitzMax", slug: "blitzmax" },
    { name: "Bluespec", slug: "bluespec" },
    { name: "Bluespec BH", slug: "bluespec-bh" },
    { name: "Boo", slug: "boo" },
    { name: "Boogie", slug: "boogie" },
    { name: "Brainfuck", slug: "brainfuck" },
    { name: "BrighterScript", slug: "brighterscript" },
    { name: "Brightscript", slug: "brightscript" },
    { name: "Zeek", slug: "zeek" },
    { name: "Browserslist", slug: "browserslist" },
    { name: "C", slug: "c" },
    { name: "C#", slug: "c%23" },
    {
        name: "C++",
        slug: "c++",
    },
    { name: "C-ObjDump", slug: "c-objdump" },
    { name: "C2hs Haskell", slug: "c2hs-haskell" },
    { name: "Cabal Config", slug: "cabal-config" },
    { name: "Cadence", slug: "cadence" },
    { name: "Cairo", slug: "cairo" },
    { name: "CameLIGO", slug: "cameligo" },
    { name: "CAP CDS", slug: "cap-cds" },
    { name: "Cap'n Proto", slug: "cap'n-proto" },
    { name: "CartoCSS", slug: "cartocss" },
    { name: "Ceylon", slug: "ceylon" },
    { name: "Chapel", slug: "chapel" },
    { name: "Charity", slug: "charity" },
    { name: "Checksums", slug: "checksums" },
    { name: "ChucK", slug: "chuck" },
    { name: "CIL", slug: "cil" },
    { name: "Circom", slug: "circom" },
    { name: "Cirru", slug: "cirru" },
    { name: "Clarion", slug: "clarion" },
    { name: "Clarity", slug: "clarity" },
    { name: "Classic ASP", slug: "classic-asp" },
    { name: "Clean", slug: "clean" },
    { name: "Click", slug: "click" },
    { name: "CLIPS", slug: "clips" },
    {
        name: "Clojure",
        slug: "clojure",
    },
    { name: "Closure Templates", slug: "closure-templates" },
    {
        name: "Cloud Firestore Security Rules",
        slug: "cloud-firestore-security-rules",
    },
    { name: "CMake", slug: "cmake" },
    { name: "COBOL", slug: "cobol" },
    { name: "CODEOWNERS", slug: "codeowners" },
    { name: "CodeQL", slug: "codeql" },
    { name: "CoffeeScript", slug: "coffeescript" },
    { name: "ColdFusion", slug: "coldfusion" },
    { name: "ColdFusion CFC", slug: "coldfusion-cfc" },
    { name: "COLLADA", slug: "collada" },
    { name: "Common Lisp", slug: "common-lisp" },
    { name: "Common Workflow Language", slug: "common-workflow-language" },
    { name: "Component Pascal", slug: "component-pascal" },
    { name: "CoNLL-U", slug: "conll-u" },
    { name: "Cool", slug: "cool" },
    { name: "Coq", slug: "coq" },
    { name: "Cpp-ObjDump", slug: "cpp-objdump" },
    { name: "Creole", slug: "creole" },
    { name: "Crystal", slug: "crystal" },
    { name: "CSON", slug: "cson" },
    {
        name: "Csound",
        slug: "csound",
    },
    { name: "Csound Document", slug: "csound-document" },
    { name: "Csound Score", slug: "csound-score" },
    { name: "CSS", slug: "css" },
    { name: "CSV", slug: "csv" },
    { name: "Cuda", slug: "cuda" },
    { name: "CUE", slug: "cue" },
    { name: "Cue Sheet", slug: "cue-sheet" },
    { name: "cURL Config", slug: "curl-config" },
    { name: "Curry", slug: "curry" },
    { name: "CWeb", slug: "cweb" },
    { name: "Cycript", slug: "cycript" },
    { name: "Cypher", slug: "cypher" },
    { name: "Cython", slug: "cython" },
    { name: "D", slug: "d" },
    { name: "D-ObjDump", slug: "d-objdump" },
    { name: "D2", slug: "d2" },
    { name: "Dafny", slug: "dafny" },
    { name: "Darcs Patch", slug: "darcs-patch" },
    { name: "Dart", slug: "dart" },
    { name: "DataWeave", slug: "dataweave" },
    { name: "Debian Package Control File", slug: "debian-package-control-file" },
    { name: "DenizenScript", slug: "denizenscript" },
    { name: "desktop", slug: "desktop" },
    {
        name: "Dhall",
        slug: "dhall",
    },
    { name: "Diff", slug: "diff" },
    { name: "DIGITAL Command Language", slug: "digital-command-language" },
    { name: "dircolors", slug: "dircolors" },
    { name: "DirectX 3D File", slug: "directx-3d-file" },
    { name: "DM", slug: "dm" },
    { name: "DNS Zone", slug: "dns-zone" },
    { name: "Dockerfile", slug: "dockerfile" },
    { name: "Dogescript", slug: "dogescript" },
    { name: "Dotenv", slug: "dotenv" },
    { name: "DTrace", slug: "dtrace" },
    { name: "Dylan", slug: "dylan" },
    { name: "E", slug: "e" },
    { name: "E-mail", slug: "e-mail" },
    { name: "Eagle", slug: "eagle" },
    { name: "Earthly", slug: "earthly" },
    { name: "Easybuild", slug: "easybuild" },
    { name: "EBNF", slug: "ebnf" },
    { name: "eC", slug: "ec" },
    { name: "Ecere Projects", slug: "ecere-projects" },
    { name: "ECL", slug: "ecl" },
    { name: "ECLiPSe", slug: "eclipse" },
    { name: "Ecmarkup", slug: "ecmarkup" },
    { name: "EditorConfig", slug: "editorconfig" },
    {
        name: "Edje Data Collection",
        slug: "edje-data-collection",
    },
    { name: "edn", slug: "edn" },
    { name: "Eiffel", slug: "eiffel" },
    { name: "EJS", slug: "ejs" },
    { name: "Elixir", slug: "elixir" },
    { name: "Elm", slug: "elm" },
    { name: "Elvish", slug: "elvish" },
    { name: "Elvish Transcript", slug: "elvish-transcript" },
    { name: "Emacs Lisp", slug: "emacs-lisp" },
    { name: "EmberScript", slug: "emberscript" },
    { name: "E-mail", slug: "e-mail" },
    { name: "EQ", slug: "eq" },
    { name: "Erlang", slug: "erlang" },
    { name: "Euphoria", slug: "euphoria" },
    { name: "F#", slug: "f%23" },
    { name: "F*", slug: "f*" },
    { name: "Factor", slug: "factor" },
    { name: "Fancy", slug: "fancy" },
    { name: "Fantom", slug: "fantom" },
    { name: "Faust", slug: "faust" },
    { name: "Fennel", slug: "fennel" },
    { name: "FIGlet Font", slug: "figlet-font" },
    { name: "Filebench WML", slug: "filebench-wml" },
    { name: "Filterscript", slug: "filterscript" },
    { name: "fish", slug: "fish" },
    {
        name: "Fluent",
        slug: "fluent",
    },
    { name: "FLUX", slug: "flux" },
    { name: "Formatted", slug: "formatted" },
    { name: "Forth", slug: "forth" },
    { name: "Fortran", slug: "fortran" },
    { name: "Fortran Free Form", slug: "fortran-free-form" },
    { name: "FreeBasic", slug: "freebasic" },
    { name: "FreeMarker", slug: "freemarker" },
    { name: "Frege", slug: "frege" },
    { name: "Futhark", slug: "futhark" },
    { name: "G-code", slug: "g-code" },
    { name: "Game Maker Language", slug: "game-maker-language" },
    { name: "GAML", slug: "gaml" },
    { name: "GAMS", slug: "gams" },
    { name: "GAP", slug: "gap" },
    { name: "GCC Machine Description", slug: "gcc-machine-description" },
    { name: "GDB", slug: "gdb" },
    { name: "GDScript", slug: "gdscript" },
    { name: "GEDCOM", slug: "gedcom" },
    { name: "Gemfile.lock", slug: "gemfile.lock" },
    { name: "Gemini", slug: "gemini" },
    { name: "Genero", slug: "genero" },
    { name: "Genero Forms", slug: "genero-forms" },
    { name: "Genie", slug: "genie" },
    {
        name: "Genshi",
        slug: "genshi",
    },
    { name: "Gentoo Ebuild", slug: "gentoo-ebuild" },
    { name: "Gentoo Eclass", slug: "gentoo-eclass" },
    { name: "Gerber Image", slug: "gerber-image" },
    { name: "Gettext Catalog", slug: "gettext-catalog" },
    { name: "Gherkin", slug: "gherkin" },
    { name: "Git Attributes", slug: "git-attributes" },
    { name: "Git Config", slug: "git-config" },
    { name: "Git Revision List", slug: "git-revision-list" },
    { name: "Gleam", slug: "gleam" },
    { name: "GLSL", slug: "glsl" },
    { name: "Glyph", slug: "glyph" },
    {
        name: "Glyph Bitmap Distribution Format",
        slug: "glyph-bitmap-distribution-format",
    },
    { name: "GN", slug: "gn" },
    { name: "Gnuplot", slug: "gnuplot" },
    { name: "Go", slug: "go" },
    { name: "Go Checksums", slug: "go-checksums" },
    { name: "Go Module", slug: "go-module" },
    { name: "Go Workspace", slug: "go-workspace" },
    { name: "Godot Resource", slug: "godot-resource" },
    { name: "Golo", slug: "golo" },
    { name: "Gosu", slug: "gosu" },
    {
        name: "Grace",
        slug: "grace",
    },
    { name: "Gradle", slug: "gradle" },
    { name: "Gradle Kotlin DSL", slug: "gradle-kotlin-dsl" },
    { name: "Grammatical Framework", slug: "grammatical-framework" },
    { name: "Graph Modeling Language", slug: "graph-modeling-language" },
    { name: "GraphQL", slug: "graphql" },
    { name: "Graphviz (DOT)", slug: "graphviz-(dot)" },
    { name: "Groovy", slug: "groovy" },
    { name: "Groovy Server Pages", slug: "groovy-server-pages" },
    { name: "GSC", slug: "gsc" },
    { name: "Hack", slug: "hack" },
    { name: "Haml", slug: "haml" },
    { name: "Handlebars", slug: "handlebars" },
    { name: "HAProxy", slug: "haproxy" },
    { name: "Harbour", slug: "harbour" },
    { name: "Haskell", slug: "haskell" },
    { name: "Haxe", slug: "haxe" },
    { name: "HCL", slug: "hcl" },
    { name: "HiveQL", slug: "hiveql" },
    { name: "HLSL", slug: "hlsl" },
    { name: "HOCON", slug: "hocon" },
    { name: "HolyC", slug: "holyc" },
    { name: "hoon", slug: "hoon" },
    {
        name: "Hosts File",
        slug: "hosts-file",
    },
    { name: "HTML", slug: "html" },
    { name: "Jinja", slug: "jinja" },
    { name: "HTML+ECR", slug: "html+ecr" },
    { name: "HTML+EEX", slug: "html+eex" },
    { name: "HTML+ERB", slug: "html+erb" },
    { name: "HTML+PHP", slug: "html+php" },
    { name: "HTML+Razor", slug: "html+razor" },
    { name: "HTTP", slug: "http" },
    { name: "HXML", slug: "hxml" },
    { name: "Hy", slug: "hy" },
    { name: "HyPhy", slug: "hyphy" },
    { name: "IDL", slug: "idl" },
    { name: "Idris", slug: "idris" },
    { name: "Ignore List", slug: "ignore-list" },
    { name: "IGOR Pro", slug: "igor-pro" },
    { name: "ImageJ Macro", slug: "imagej-macro" },
    { name: "Imba", slug: "imba" },
    { name: "Inform 7", slug: "inform-7" },
    { name: "INI", slug: "ini" },
    { name: "Ink", slug: "ink" },
    { name: "Inno Setup", slug: "inno-setup" },
    { name: "Io", slug: "io" },
    { name: "Ioke", slug: "ioke" },
    { name: "IRC log", slug: "irc-log" },
    { name: "Isabelle", slug: "isabelle" },
    {
        name: "Isabelle ROOT",
        slug: "isabelle-root",
    },
    { name: "J", slug: "j" },
    { name: "Janet", slug: "janet" },
    { name: "JAR Manifest", slug: "jar-manifest" },
    { name: "Jasmin", slug: "jasmin" },
    { name: "Java", slug: "java" },
    { name: "Java Properties", slug: "java-properties" },
    { name: "Java Server Pages", slug: "java-server-pages" },
    { name: "JavaScript", slug: "javascript" },
    { name: "TypeScript", slug: "typescript" },
    { name: "JavaScript+ERB", slug: "javascript+erb" },
    { name: "JCL", slug: "jcl" },
    { name: "Jest Snapshot", slug: "jest-snapshot" },
    { name: "JetBrains MPS", slug: "jetbrains-mps" },
    { name: "JFlex", slug: "jflex" },
    { name: "Jinja", slug: "jinja" },
    { name: "Jison", slug: "jison" },
    { name: "Jison Lex", slug: "jison-lex" },
    { name: "Jolie", slug: "jolie" },
    { name: "jq", slug: "jq" },
    { name: "JSON", slug: "json" },
    { name: "JSON with Comments", slug: "json-with-comments" },
    { name: "JSON5", slug: "json5" },
    { name: "JSONiq", slug: "jsoniq" },
    { name: "JSONLD", slug: "jsonld" },
    {
        name: "Jsonnet",
        slug: "jsonnet",
    },
    { name: "Julia", slug: "julia" },
    { name: "Jupyter Notebook", slug: "jupyter-notebook" },
    { name: "Just", slug: "just" },
    { name: "Kaitai Struct", slug: "kaitai-struct" },
    { name: "KakouneScript", slug: "kakounescript" },
    { name: "KerboScript", slug: "kerboscript" },
    { name: "KiCad Layout", slug: "kicad-layout" },
    { name: "KiCad Legacy Layout", slug: "kicad-legacy-layout" },
    { name: "KiCad Schematic", slug: "kicad-schematic" },
    { name: "Kickstart", slug: "kickstart" },
    { name: "Kit", slug: "kit" },
    { name: "Kotlin", slug: "kotlin" },
    { name: "KRL", slug: "krl" },
    { name: "Kusto", slug: "kusto" },
    { name: "kvlang", slug: "kvlang" },
    { name: "LabVIEW", slug: "labview" },
    { name: "Lark", slug: "lark" },
    { name: "Lasso", slug: "lasso" },
    { name: "Latte", slug: "latte" },
    { name: "Lean", slug: "lean" },
    { name: "Less", slug: "less" },
    { name: "Lex", slug: "lex" },
    { name: "LFE", slug: "lfe" },
    {
        name: "LigoLANG",
        slug: "ligolang",
    },
    { name: "LilyPond", slug: "lilypond" },
    { name: "Limbo", slug: "limbo" },
    { name: "Linker Script", slug: "linker-script" },
    { name: "Linux Kernel Module", slug: "linux-kernel-module" },
    { name: "Liquid", slug: "liquid" },
    { name: "Literate Agda", slug: "literate-agda" },
    { name: "Literate CoffeeScript", slug: "literate-coffeescript" },
    { name: "Literate Haskell", slug: "literate-haskell" },
    { name: "LiveScript", slug: "livescript" },
    { name: "LLVM", slug: "llvm" },
    { name: "Logos", slug: "logos" },
    { name: "Logtalk", slug: "logtalk" },
    { name: "LOLCODE", slug: "lolcode" },
    { name: "LookML", slug: "lookml" },
    { name: "LoomScript", slug: "loomscript" },
    { name: "LSL", slug: "lsl" },
    { name: "LTspice Symbol", slug: "ltspice-symbol" },
    { name: "Lua", slug: "lua" },
    { name: "M", slug: "m" },
    { name: "M4", slug: "m4" },
    { name: "M4Sugar", slug: "m4sugar" },
    { name: "Macaulay2", slug: "macaulay2" },
    {
        name: "Makefile",
        slug: "makefile",
    },
    { name: "Mako", slug: "mako" },
    { name: "Markdown", slug: "markdown" },
    { name: "Marko", slug: "marko" },
    { name: "Mask", slug: "mask" },
    { name: "Mathematica", slug: "mathematica" },
    { name: "MATLAB", slug: "matlab" },
    { name: "Maven POM", slug: "maven-pom" },
    { name: "Max", slug: "max" },
    { name: "MAXScript", slug: "maxscript" },
    { name: "mcfunction", slug: "mcfunction" },
    { name: "MDX", slug: "mdx" },
    { name: "Wikitext", slug: "wikitext" },
    { name: "Mercury", slug: "mercury" },
    { name: "Mermaid", slug: "mermaid" },
    { name: "Meson", slug: "meson" },
    { name: "Metal", slug: "metal" },
    {
        name: "Microsoft Developer Studio Project",
        slug: "microsoft-developer-studio-project",
    },
    {
        name: "Microsoft Visual Studio Solution",
        slug: "microsoft-visual-studio-solution",
    },
    { name: "MiniD", slug: "minid" },
    { name: "MiniYAML", slug: "miniyaml" },
    { name: "Mint", slug: "mint" },
    { name: "Mirah", slug: "mirah" },
    {
        name: "mIRC Script",
        slug: "mirc-script",
    },
    { name: "MLIR", slug: "mlir" },
    { name: "Modelica", slug: "modelica" },
    { name: "Modula-2", slug: "modula-2" },
    { name: "Modula-3", slug: "modula-3" },
    { name: "Module Management System", slug: "module-management-system" },
    { name: "Monkey", slug: "monkey" },
    { name: "Monkey C", slug: "monkey-c" },
    { name: "Moocode", slug: "moocode" },
    { name: "MoonScript", slug: "moonscript" },
    { name: "Motoko", slug: "motoko" },
    { name: "Motorola 68K Assembly", slug: "motorola-68k-assembly" },
    { name: "Move", slug: "move" },
    { name: "MQL4", slug: "mql4" },
    { name: "MQL5", slug: "mql5" },
    { name: "MTML", slug: "mtml" },
    { name: "MUF", slug: "muf" },
    { name: "mupad", slug: "mupad" },
    { name: "Muse", slug: "muse" },
    { name: "Mustache", slug: "mustache" },
    { name: "Myghty", slug: "myghty" },
    { name: "nanorc", slug: "nanorc" },
    { name: "Nasal", slug: "nasal" },
    { name: "NASL", slug: "nasl" },
    { name: "NCL", slug: "ncl" },
    {
        name: "Nearley",
        slug: "nearley",
    },
    { name: "Nemerle", slug: "nemerle" },
    { name: "NEON", slug: "neon" },
    { name: "nesC", slug: "nesc" },
    { name: "NetLinx", slug: "netlinx" },
    { name: "NetLinx+ERB", slug: "netlinx+erb" },
    { name: "NetLogo", slug: "netlogo" },
    { name: "NewLisp", slug: "newlisp" },
    { name: "Nextflow", slug: "nextflow" },
    { name: "Nginx", slug: "nginx" },
    { name: "Nim", slug: "nim" },
    { name: "Ninja", slug: "ninja" },
    { name: "Nit", slug: "nit" },
    { name: "Nix", slug: "nix" },
    { name: "NL", slug: "nl" },
    { name: "NPM Config", slug: "npm-config" },
    { name: "NSIS", slug: "nsis" },
    { name: "Nu", slug: "nu" },
    { name: "NumPy", slug: "numpy" },
    { name: "Nunjucks", slug: "nunjucks" },
    { name: "Nushell", slug: "nushell" },
    { name: "NWScript", slug: "nwscript" },
    { name: "OASv2-json", slug: "oasv2-json" },
    { name: "OASv2-yaml", slug: "oasv2-yaml" },
    { name: "OASv3-json", slug: "oasv3-json" },
    { name: "OASv3-yaml", slug: "oasv3-yaml" },
    {
        name: "ObjDump",
        slug: "objdump",
    },
    {
        name: "Object Data Instance Notation",
        slug: "object-data-instance-notation",
    },
    { name: "Objective-C", slug: "objective-c" },
    { name: "Objective-C++", slug: "objective-c++" },
    { name: "Objective-J", slug: "objective-j" },
    { name: "ObjectScript", slug: "objectscript" },
    { name: "OCaml", slug: "ocaml" },
    { name: "Odin", slug: "odin" },
    { name: "Omgrofl", slug: "omgrofl" },
    { name: "ooc", slug: "ooc" },
    { name: "Opa", slug: "opa" },
    { name: "Opal", slug: "opal" },
    { name: "Open Policy Agent", slug: "open-policy-agent" },
    { name: "OpenAPI Specification v2", slug: "openapi-specification-v2" },
    { name: "OpenAPI Specification v3", slug: "openapi-specification-v3" },
    { name: "OpenCL", slug: "opencl" },
    { name: "OpenEdge ABL", slug: "openedge-abl" },
    { name: "OpenQASM", slug: "openqasm" },
    { name: "OpenRC runscript", slug: "openrc-runscript" },
    { name: "OpenSCAD", slug: "openscad" },
    {
        name: "OpenStep Property List",
        slug: "openstep-property-list",
    },
    { name: "OpenType Feature File", slug: "opentype-feature-file" },
    { name: "Option List", slug: "option-list" },
    { name: "Org", slug: "org" },
    { name: "Ox", slug: "ox" },
    { name: "Oxygene", slug: "oxygene" },
    { name: "Oz", slug: "oz" },
    { name: "P4", slug: "p4" },
    { name: "Pact", slug: "pact" },
    { name: "Pan", slug: "pan" },
    { name: "Papyrus", slug: "papyrus" },
    { name: "Parrot", slug: "parrot" },
    { name: "Parrot Assembly", slug: "parrot-assembly" },
    {
        name: "Parrot Internal Representation",
        slug: "parrot-internal-representation",
    },
    { name: "Pascal", slug: "pascal" },
    { name: "Pawn", slug: "pawn" },
    { name: "PDDL", slug: "pddl" },
    { name: "PEG.js", slug: "peg.js" },
    { name: "Pep8", slug: "pep8" },
    { name: "Perl", slug: "perl" },
    { name: "PHP", slug: "php" },
    { name: "Pic", slug: "pic" },
    { name: "Pickle", slug: "pickle" },
    { name: "PicoLisp", slug: "picolisp" },
    { name: "PigLatin", slug: "piglatin" },
    {
        name: "Pike",
        slug: "pike",
    },
    { name: "PlantUML", slug: "plantuml" },
    { name: "PLpgSQL", slug: "plpgsql" },
    { name: "PLSQL", slug: "plsql" },
    { name: "Pod", slug: "pod" },
    { name: "Pod 6", slug: "pod-6" },
    { name: "PogoScript", slug: "pogoscript" },
    { name: "Polar", slug: "polar" },
    { name: "Pony", slug: "pony" },
    { name: "Portugol", slug: "portugol" },
    { name: "PostCSS", slug: "postcss" },
    { name: "PostScript", slug: "postscript" },
    { name: "POV-Ray SDL", slug: "pov-ray-sdl" },
    { name: "PowerBuilder", slug: "powerbuilder" },
    { name: "PowerShell", slug: "powershell" },
    { name: "Prisma", slug: "prisma" },
    { name: "Processing", slug: "processing" },
    { name: "Procfile", slug: "procfile" },
    { name: "Proguard", slug: "proguard" },
    { name: "Prolog", slug: "prolog" },
    { name: "Promela", slug: "promela" },
    { name: "Propeller Spin", slug: "propeller-spin" },
    { name: "Protocol Buffer", slug: "protocol-buffer" },
    {
        name: "Protocol Buffer Text Format",
        slug: "protocol-buffer-text-format",
    },
    { name: "Public Key", slug: "public-key" },
    { name: "Pug", slug: "pug" },
    { name: "Puppet", slug: "puppet" },
    { name: "Pure Data", slug: "pure-data" },
    { name: "PureBasic", slug: "purebasic" },
    { name: "PureScript", slug: "purescript" },
    { name: "Pyret", slug: "pyret" },
    { name: "Python", slug: "python" },
    { name: "Python console", slug: "python-console" },
    { name: "Python traceback", slug: "python-traceback" },
    { name: "q", slug: "q" },
    { name: "Q#", slug: "q%23" },
    { name: "QMake", slug: "qmake" },
    { name: "QML", slug: "qml" },
    { name: "Qt Script", slug: "qt-script" },
    { name: "Quake", slug: "quake" },
    { name: "R", slug: "r" },
    { name: "Racket", slug: "racket" },
    { name: "Ragel", slug: "ragel" },
    { name: "Raku", slug: "raku" },
    { name: "RAML", slug: "raml" },
    { name: "Rascal", slug: "rascal" },
    { name: "Raw token data", slug: "raw-token-data" },
    { name: "RBS", slug: "rbs" },
    {
        name: "RDoc",
        slug: "rdoc",
    },
    { name: "Readline Config", slug: "readline-config" },
    { name: "REALbasic", slug: "realbasic" },
    { name: "Reason", slug: "reason" },
    { name: "ReasonLIGO", slug: "reasonligo" },
    { name: "Rebol", slug: "rebol" },
    { name: "Record Jar", slug: "record-jar" },
    { name: "Red", slug: "red" },
    { name: "Redcode", slug: "redcode" },
    { name: "Redirect Rules", slug: "redirect-rules" },
    { name: "Regular Expression", slug: "regular-expression" },
    { name: "Ren'Py", slug: "ren'py" },
    { name: "RenderScript", slug: "renderscript" },
    { name: "ReScript", slug: "rescript" },
    { name: "reStructuredText", slug: "restructuredtext" },
    { name: "REXX", slug: "rexx" },
    { name: "Rez", slug: "rez" },
    { name: "Rich Text Format", slug: "rich-text-format" },
    { name: "Ring", slug: "ring" },
    { name: "Riot", slug: "riot" },
    { name: "RMarkdown", slug: "rmarkdown" },
    { name: "RobotFramework", slug: "robotframework" },
    { name: "robots.txt", slug: "robots.txt" },
    {
        name: "Roff",
        slug: "roff",
    },
    { name: "Roff Manpage", slug: "roff-manpage" },
    { name: "Rouge", slug: "rouge" },
    { name: "RouterOS Script", slug: "routeros-script" },
    { name: "RPC", slug: "rpc" },
    { name: "RPGLE", slug: "rpgle" },
    { name: "RPM Spec", slug: "rpm-spec" },
    { name: "Ruby", slug: "ruby" },
    { name: "RUNOFF", slug: "runoff" },
    { name: "Rust", slug: "rust" },
    { name: "Sage", slug: "sage" },
    { name: "SaltStack", slug: "saltstack" },
    { name: "SAS", slug: "sas" },
    { name: "Sass", slug: "sass" },
    { name: "Scala", slug: "scala" },
    { name: "Scaml", slug: "scaml" },
    { name: "Scenic", slug: "scenic" },
    { name: "Scheme", slug: "scheme" },
    { name: "Scilab", slug: "scilab" },
    { name: "SCSS", slug: "scss" },
    { name: "sed", slug: "sed" },
    { name: "Self", slug: "self" },
    { name: "SELinux Policy", slug: "selinux-policy" },
    { name: "ShaderLab", slug: "shaderlab" },
    { name: "Shell", slug: "shell" },
    {
        name: "ShellCheck Config",
        slug: "shellcheck-config",
    },
    { name: "ShellSession", slug: "shellsession" },
    { name: "Shen", slug: "shen" },
    { name: "Sieve", slug: "sieve" },
    { name: "Simple File Verification", slug: "simple-file-verification" },
    { name: "Singularity", slug: "singularity" },
    { name: "Slash", slug: "slash" },
    { name: "Slice", slug: "slice" },
    { name: "Slim", slug: "slim" },
    { name: "Smali", slug: "smali" },
    { name: "Smalltalk", slug: "smalltalk" },
    { name: "Smarty", slug: "smarty" },
    { name: "Smithy", slug: "smithy" },
    { name: "SmPL", slug: "smpl" },
    { name: "SMT", slug: "smt" },
    { name: "Snakemake", slug: "snakemake" },
    { name: "Solidity", slug: "solidity" },
    { name: "Soong", slug: "soong" },
    { name: "SourcePawn", slug: "sourcepawn" },
    { name: "SPARQL", slug: "sparql" },
    { name: "Spline Font Database", slug: "spline-font-database" },
    { name: "SQF", slug: "sqf" },
    { name: "SQL", slug: "sql" },
    { name: "SQLPL", slug: "sqlpl" },
    {
        name: "Squirrel",
        slug: "squirrel",
    },
    { name: "SRecode Template", slug: "srecode-template" },
    { name: "SSH Config", slug: "ssh-config" },
    { name: "Stan", slug: "stan" },
    { name: "Standard ML", slug: "standard-ml" },
    { name: "STAR", slug: "star" },
    { name: "Starlark", slug: "starlark" },
    { name: "Stata", slug: "stata" },
    { name: "STL", slug: "stl" },
    { name: "STON", slug: "ston" },
    { name: "StringTemplate", slug: "stringtemplate" },
    { name: "Stylus", slug: "stylus" },
    { name: "SubRip Text", slug: "subrip-text" },
    { name: "SugarSS", slug: "sugarss" },
    { name: "SuperCollider", slug: "supercollider" },
    { name: "Svelte", slug: "svelte" },
    { name: "SVG", slug: "svg" },
    { name: "Sway", slug: "sway" },
    { name: "Sweave", slug: "sweave" },
    { name: "Swift", slug: "swift" },
    { name: "SWIG", slug: "swig" },
    { name: "SystemVerilog", slug: "systemverilog" },
    { name: "Talon", slug: "talon" },
    { name: "Tcl", slug: "tcl" },
    { name: "Tcsh", slug: "tcsh" },
    {
        name: "Tea",
        slug: "tea",
    },
    { name: "Terra", slug: "terra" },
    { name: "TeX", slug: "tex" },
    { name: "Texinfo", slug: "texinfo" },
    { name: "Text", slug: "text" },
    { name: "Textile", slug: "textile" },
    { name: "TextMate Properties", slug: "textmate-properties" },
    { name: "Thrift", slug: "thrift" },
    { name: "TI Program", slug: "ti-program" },
    { name: "TL-Verilog", slug: "tl-verilog" },
    { name: "TLA", slug: "tla" },
    { name: "TOML", slug: "toml" },
    { name: "TSQL", slug: "tsql" },
    { name: "TSV", slug: "tsv" },
    { name: "TSX", slug: "tsx" },
    { name: "Turing", slug: "turing" },
    { name: "Turtle", slug: "turtle" },
    { name: "Twig", slug: "twig" },
    { name: "TXL", slug: "txl" },
    { name: "Type Language", slug: "type-language" },
    { name: "Typst", slug: "typst" },
    { name: "Unified Parallel C", slug: "unified-parallel-c" },
    { name: "Unity3D Asset", slug: "unity3d-asset" },
    { name: "Unix Assembly", slug: "unix-assembly" },
    { name: "Uno", slug: "uno" },
    {
        name: "UnrealScript",
        slug: "unrealscript",
    },
    { name: "UrWeb", slug: "urweb" },
    { name: "V", slug: "v" },
    { name: "Vala", slug: "vala" },
    { name: "Valve Data Format", slug: "valve-data-format" },
    { name: "VBA", slug: "vba" },
    { name: "VBScript", slug: "vbscript" },
    { name: "VCL", slug: "vcl" },
    { name: "Velocity Template Language", slug: "velocity-template-language" },
    { name: "Verilog", slug: "verilog" },
    { name: "VHDL", slug: "vhdl" },
    { name: "Vim Help File", slug: "vim-help-file" },
    { name: "Vim Script", slug: "vim-script" },
    { name: "Vim Snippet", slug: "vim-snippet" },
    { name: "Visual Basic .NET", slug: "visual-basic-.net" },
    { name: "Visual Basic .NET", slug: "visual-basic-.net" },
    { name: "Visual Basic 6.0", slug: "visual-basic-6.0" },
    { name: "Volt", slug: "volt" },
    { name: "Vue", slug: "vue" },
    { name: "Vyper", slug: "vyper" },
    { name: "Wavefront Material", slug: "wavefront-material" },
    { name: "Wavefront Object", slug: "wavefront-object" },
    {
        name: "WDL",
        slug: "wdl",
    },
    { name: "Web Ontology Language", slug: "web-ontology-language" },
    { name: "WebAssembly", slug: "webassembly" },
    { name: "WebAssembly Interface Type", slug: "webassembly-interface-type" },
    { name: "WebIDL", slug: "webidl" },
    { name: "WebVTT", slug: "webvtt" },
    { name: "Wget Config", slug: "wget-config" },
    { name: "WGSL", slug: "wgsl" },
    { name: "Whiley", slug: "whiley" },
    { name: "Wikitext", slug: "wikitext" },
    { name: "Win32 Message File", slug: "win32-message-file" },
    { name: "Windows Registry Entries", slug: "windows-registry-entries" },
    { name: "wisp", slug: "wisp" },
    { name: "Witcher Script", slug: "witcher-script" },
    { name: "Wollok", slug: "wollok" },
    {
        name: "World of Warcraft Addon Data",
        slug: "world-of-warcraft-addon-data",
    },
    { name: "Wren", slug: "wren" },
    { name: "X BitMap", slug: "x-bitmap" },
    { name: "X Font Directory Index", slug: "x-font-directory-index" },
    { name: "X PixMap", slug: "x-pixmap" },
    {
        name: "X10",
        slug: "x10",
    },
    { name: "xBase", slug: "xbase" },
    { name: "XC", slug: "xc" },
    { name: "XCompose", slug: "xcompose" },
    { name: "XML", slug: "xml" },
    { name: "XML Property List", slug: "xml-property-list" },
    { name: "Xojo", slug: "xojo" },
    { name: "Xonsh", slug: "xonsh" },
    { name: "XPages", slug: "xpages" },
    { name: "XProc", slug: "xproc" },
    { name: "XQuery", slug: "xquery" },
    { name: "XS", slug: "xs" },
    { name: "XSLT", slug: "xslt" },
    { name: "Xtend", slug: "xtend" },
    { name: "Yacc", slug: "yacc" },
    { name: "YAML", slug: "yaml" },
    { name: "YANG", slug: "yang" },
    { name: "YARA", slug: "yara" },
    { name: "YASnippet", slug: "yasnippet" },
    { name: "Yul", slug: "yul" },
    { name: "ZAP", slug: "zap" },
    { name: "Zeek", slug: "zeek" },
    { name: "ZenScript", slug: "zenscript" },
    { name: "Zephir", slug: "zephir" },
    { name: "Zig", slug: "zig" },
    { name: "ZIL", slug: "zil" },
    { name: "Zimpl", slug: "zimpl" },
];